#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -m 1 &
pgrep -x dunst > /dev/null || dunst &

bspc monitor -d x x x x x x

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
